export enum ETypesActionsGame {
	SET_PLAYER = '[Game] SET_PLAYER',
	SET_SCORE = '[Game] SET_SCORE',
	RESET_SCORE = '[Game] RESET_SCORE',
	SET_MODE_GAME = '[Game] SET_MODE_GAME',
	INCREMENT_MODE_GAME_TOTAL = '[Game] INCREMENT_MODE_GAME_TOTAL',
	DECREMENT_MODE_GAME_TOTAL = '[Game] DECREMENT_MODE_GAME_TOTAL',
}
